version: "3"

services:
  airflow:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: airflow_standalone
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@airflow_postgres:5432/airflow
      - PYTHONPATH=/opt/airflow
    depends_on:
      - postgres
    ports:
      - "8082:8080"
    command: >
      bash -c "
        airflow db init &&
        airflow users create --username airflow --password airflow --firstname airflow --lastname airflow --role Admin --email your_email@example.com &&
        airflow scheduler &
        airflow webserver
      "
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./utils:/opt/airflow/utils
      - ./tasks:/opt/airflow/tasks
      - ./data:/opt/airflow/data
  
  postgres:
    image: postgres:13
    container_name: airflow_postgres
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data